name: Backend Production Deployment
env:
  VERCEL_ORG_ID: Q8esKtg3ENB1XkeFyRo5lqJs
  VERCEL_PROJECT_ID: prj_3O4cBn6fbexHbwdgTm9nMbAQbpDB
on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps: #wtf bro x5
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Install Vercel CLI
        run: npm install --global vercel@latest


      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=DIj85LauZRme4719HVZRZZTn


      - name: Build Project Artifacts
        run: vercel build --prod --token=DIj85LauZRme4719HVZRZZTn


      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=DIj85LauZRme4719HVZRZZTn